### ISSUE TITLE
Choosing a memory card slot in Dynamite Cop causes a crash. 

### ISSUE THREAD

**Issue by kurayami6** [inolen/redream#250]
Pretty self explanatory.

Windows 7, i5, GTX 970.

**Comment by inolen** [comment]
It looks like Dynamite Cop freaks out if the VMU isn't registered with meta data setup for the LCD display.

**Comment by inolen** [comment]
Should be fixed with https://github.com/inolen/redream/commit/a8501a2f6245efa375dbdffcdd812981546b5a32.

**Comment by kurayami6** [comment]
Still crashes.

![capture](https://user-images.githubusercontent.com/31968468/33232345-cc5c8b0a-d258-11e7-980f-2e37b6de8c9b.PNG)

**Comment by inolen** [comment]
Could you paste your log output? I think the new CI setup may have just not pushed the new version.

**Comment by kurayami6** [comment]
![capture](https://user-images.githubusercontent.com/31968468/33232769-dc4e1946-d25f-11e7-9d3d-db9330293706.PNG)

**Comment by inolen** [comment]
CI should be fixed now and this _should_ work.

**Comment by kurayami6** [comment]
Yeah it's fixed now. Thanks.
