### ISSUE TITLE
sh4: MMU not currently supported

### ISSUE THREAD

**Issue by Marc34** [inolen/redream#85]
Hi

Several games crash with this message : 

MMU not currently supported.

18 Wheeler: American Pro Trucker
90 Minutes - Sega Championship Football
Bust-A-Move 4
Resident Evil 2
Sega Rally 2

**Comment by inolen** [comment]
MMU support is currently pretty low on my priority list, although I do want to get it added eventually.

**Comment by Marc34** [comment]
OK. I made a list here : #37

**Comment by Marc34** [comment]
+ Outrigger
Ooga Booga

**Comment by inolen** [comment]
Note, @skmp added partial MMU support in https://github.com/inolen/redream/commit/3fade7f1fb0cdd5f599ca90773d4202ee6cd4202 which at least gets Ikaruga running.

**Comment by Marc34** [comment]
I see that : 18 Wheeler starts now too.

**Comment by Marc34** [comment]
- Armada
- Bang! Gunship Elite

**Comment by Marc34** [comment]
Championship Surfer : MMU not fully supported. sh4_mmu_utlb_sync memory mapping not supported. unexpected write to 0x0000000c. unhandled invalid instruction at 0x000067f0

**Comment by Marc34** [comment]
+ Ducati World Racing Challenge

**Comment by skmp** [comment]
Most non-wince games should be working now. WinCE and Bleemcast require full mmu support which is more involved.

**Comment by Marc34** [comment]
18 Wheeler and Sega Championship Football start now, thank for your work.

**Comment by bigboo3000** [comment]
Some other games that are still not working : sh4_mmu_utlb_sync memory mapping not supported:
Armada
F355 Challenge - Passione Rossa
Le Mans 24 Hours
Metropolis Street Racer
